"""Safe LaTeX pre-generation workflow for OT Math requests."""

from __future__ import annotations

import re
import shutil
import subprocess
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from otmath import MathOperation, MathRequest, render_steps_latex, run_request
from otmath.errors import OTMathError

_REQUEST_ID_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
_COMPUTE_PATTERN = re.compile(
    r"\\OTMathCompute"
    r"(?:\[(?P<options>[^\]]*)\])?"
    r"\{(?P<id>[^{}]+)\}"
    r"\{(?P<operation>[^{}]+)\}"
    r"\{(?P<expression>[^{}]+)\}"
)
_EXPLAIN_PATTERN = re.compile(
    r"\\OTMathExplain"
    r"(?:\[(?P<options>[^\]]*)\])?"
    r"\{(?P<id>[^{}]+)\}"
    r"\{(?P<expression>[^{}]+)\}"
)
_OPERATION_ALIASES = {
    "diff": MathOperation.DIFFERENTIATE,
    "differentiate": MathOperation.DIFFERENTIATE,
    "system": MathOperation.SOLVE_SYSTEM,
    "solve_system": MathOperation.SOLVE_SYSTEM,
}


class LatexBuildError(OTMathError):
    """Raised when a LaTeX generation request cannot be completed."""


@dataclass(frozen=True)
class LatexRequest:
    """A math request discovered inside a LaTeX document."""

    request_id: str
    expression: str
    operation: MathOperation
    variable: str
    kind: str


@dataclass(frozen=True)
class LatexBuildResult:
    """Files produced by the safe LaTeX generation workflow."""

    generated_file: Path
    request_count: int
    compiled_pdf: Path | None = None


def find_latex_requests(source: str) -> list[LatexRequest]:
    """Find OT Math generation macros in a LaTeX source string."""

    matches: list[tuple[int, LatexRequest]] = []

    for match in _COMPUTE_PATTERN.finditer(source):
        options = _parse_options(match.group("options") or "")
        operation = _parse_operation(match.group("operation"))
        variable = options.get("variable", _default_variable(operation))
        matches.append(
            (
                match.start(),
                LatexRequest(
                    request_id=_validate_request_id(match.group("id")),
                    expression=match.group("expression").strip(),
                    operation=operation,
                    variable=variable,
                    kind="compute",
                ),
            )
        )

    for match in _EXPLAIN_PATTERN.finditer(source):
        options = _parse_options(match.group("options") or "")
        operation = _parse_operation(options.get("operation", "simplify"))
        variable = options.get("variable", _default_variable(operation))
        matches.append(
            (
                match.start(),
                LatexRequest(
                    request_id=_validate_request_id(match.group("id")),
                    expression=match.group("expression").strip(),
                    operation=operation,
                    variable=variable,
                    kind="explain",
                ),
            )
        )

    requests = [request for _, request in sorted(matches, key=lambda item: item[0])]
    _reject_duplicate_ids(requests)
    return requests


def generate_latex_include(
    tex_file: Path,
    *,
    output_file: Path | None = None,
) -> LatexBuildResult:
    """Generate a LaTeX include file from OT Math requests in a document."""

    source = tex_file.read_text(encoding="utf-8")
    requests = find_latex_requests(source)
    if not requests:
        raise LatexBuildError(f"No OT Math generation requests found in {tex_file}.")

    generated_file = output_file or tex_file.parent / "generated" / "otmath-results.tex"
    generated_file.parent.mkdir(parents=True, exist_ok=True)
    generated_file.write_text(render_latex_include(requests), encoding="utf-8")
    return LatexBuildResult(generated_file=generated_file, request_count=len(requests))


def render_latex_include(requests: Sequence[LatexRequest]) -> str:
    """Render a generated include file for discovered LaTeX requests."""

    lines = [
        "% Generated by otcalc latex-build.",
        "% Do not edit by hand; edit the OT Math requests in the source .tex file.",
    ]
    for request in requests:
        lines.extend(_render_definition(request))
    lines.append("")
    return "\n".join(lines)


def build_latex_document(
    tex_file: Path,
    *,
    output_file: Path | None = None,
    compile_pdf: bool = False,
    engine: str = "pdflatex",
) -> LatexBuildResult:
    """Generate the include file and optionally compile the LaTeX document."""

    result = generate_latex_include(tex_file, output_file=output_file)
    if not compile_pdf:
        return result

    compiled_pdf = compile_latex_document(tex_file, engine=engine)
    return LatexBuildResult(
        generated_file=result.generated_file,
        request_count=result.request_count,
        compiled_pdf=compiled_pdf,
    )


def compile_latex_document(tex_file: Path, *, engine: str = "pdflatex") -> Path:
    """Compile a LaTeX document with a local TeX engine."""

    executable = shutil.which(engine)
    if executable is None:
        raise LatexBuildError(f"LaTeX engine not found on PATH: {engine}")

    result = subprocess.run(
        [
            executable,
            "-interaction=nonstopmode",
            "-halt-on-error",
            tex_file.name,
        ],
        cwd=tex_file.parent,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise LatexBuildError(result.stdout + result.stderr)

    return tex_file.with_suffix(".pdf")


def _render_definition(request: LatexRequest) -> list[str]:
    content = _render_request_content(request)
    return [
        rf"\expandafter\gdef\csname OTMathGenerated@{request.request_id}\endcsname{{%",
        content,
        "}",
    ]


def _render_request_content(request: LatexRequest) -> str:
    math_request = MathRequest(
        operation=request.operation,
        expression=request.expression,
        variable=request.variable,
    )
    result = run_request(math_request)
    if request.kind == "explain":
        return "\n".join([r"\[", render_steps_latex(result.steps), r"\]"])
    return result.latex


def _parse_options(options: str) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for raw_item in options.split(";"):
        item = raw_item.strip()
        if not item:
            continue
        if "=" not in item:
            raise LatexBuildError(f"Invalid OT Math option: {item}")
        key, value = (part.strip() for part in item.split("=", maxsplit=1))
        if not key or not value:
            raise LatexBuildError(f"Invalid OT Math option: {item}")
        parsed[key] = value
    return parsed


def _parse_operation(operation: str) -> MathOperation:
    normalized = operation.strip()
    if normalized in _OPERATION_ALIASES:
        return _OPERATION_ALIASES[normalized]
    try:
        return MathOperation(normalized)
    except ValueError as exc:
        raise LatexBuildError(f"Unsupported OT Math operation in LaTeX: {operation}") from exc


def _default_variable(operation: MathOperation) -> str:
    if operation == MathOperation.SOLVE_SYSTEM:
        return "x,y"
    return "x"


def _validate_request_id(request_id: str) -> str:
    stripped = request_id.strip()
    if not _REQUEST_ID_PATTERN.fullmatch(stripped):
        raise LatexBuildError(f"Invalid OT Math request id: {request_id}")
    return stripped


def _reject_duplicate_ids(requests: Sequence[LatexRequest]) -> None:
    seen: set[str] = set()
    duplicates = set()
    for request in requests:
        if request.request_id in seen:
            duplicates.add(request.request_id)
        seen.add(request.request_id)
    if duplicates:
        names = ", ".join(sorted(duplicates))
        raise LatexBuildError(f"Duplicate OT Math request ids: {names}")
