"""Advanced deterministic math domains."""

from otmath.domains.matrices import (
    matrix_adjoint,
    matrix_cholesky_decomposition,
    matrix_columnspace,
    matrix_condition_number,
    matrix_conjugate,
    matrix_determinant,
    matrix_diagonalize,
    matrix_eigenvalues,
    matrix_eigenvectors,
    matrix_inverse,
    matrix_lu_decomposition,
    matrix_norm,
    matrix_nullspace,
    matrix_order,
    matrix_power,
    matrix_qr_decomposition,
    matrix_rank,
    matrix_rowspace,
    matrix_rref,
    matrix_solve,
    matrix_trace,
    matrix_transpose,
    parse_matrix,
    parse_matrix_pair,
)
from otmath.domains.statistics import (
    parse_dataset,
    statistics_mean,
    statistics_median,
    statistics_stdev,
    statistics_variance,
)
from otmath.domains.systems import SystemRequest, solve_system
from otmath.domains.units import convert_units, parse_unit_expression

__all__ = [
    "SystemRequest",
    "convert_units",
    "matrix_adjoint",
    "matrix_cholesky_decomposition",
    "matrix_columnspace",
    "matrix_conjugate",
    "matrix_condition_number",
    "matrix_diagonalize",
    "matrix_determinant",
    "matrix_eigenvalues",
    "matrix_eigenvectors",
    "matrix_inverse",
    "matrix_lu_decomposition",
    "matrix_nullspace",
    "matrix_norm",
    "matrix_order",
    "matrix_power",
    "matrix_qr_decomposition",
    "matrix_rank",
    "matrix_rref",
    "matrix_rowspace",
    "matrix_solve",
    "matrix_trace",
    "matrix_transpose",
    "parse_dataset",
    "parse_matrix",
    "parse_matrix_pair",
    "parse_unit_expression",
    "solve_system",
    "statistics_mean",
    "statistics_median",
    "statistics_stdev",
    "statistics_variance",
]
